### ISSUE TITLE
Dry Setting Values Inaccurate 

### ISSUE THREAD

**Issue by BenGlossop09** [Eikkargh/Candy-API-to-JSON#10]
For model H3DS4965TACBE-80, 'DryT' output values do not match values defined in the current configuration.yaml version. Correct values need to be identified and defined in the code.

**Comment by Eikkargh** [comment]
I don't think I finished checking all the drying settings on my machine. If you work out any of yours I'll happily update the yaml with them.

**Comment by BenGlossop09** [comment]
The DryT values are:
DryT=0

For reference the commands are:
Dry=0 - Dry Off
Dry=1 - Extra Dry (3hr 50min)
Dry=2 - Iron Dry (2hr 50min)
Dry=3 - Cupboard Dry (3hr 40min)
Dry=4 - UNKNOWN - Seemed to start the end phase of a dry (started with 8 mins remaining, DryT=4 (finished))
Dry=5 - 120 min
Dry=6 - 90 min
Dry=7 - 60 min
Dry=8 - 30 min

**Comment by BenGlossop09** [comment]
Full list for my model here, I've removed DryT == 4 as I have not seen it used so far. 

```
  - sensor:
      - name: 'Washer/Dryer - Dry Time'
        icon: mdi:clock-time-four
        state: >
          {% set DryT = state_attr('sensor.candy_washer_dryer', 'DryT') %}
          {% if DryT == None %}Off
          {% elif DryT == "0" %}Dry Off
          {% elif DryT == "1" %}Extra Dry 
          {% elif DryT == "2" %}Iron Dry
          {% elif DryT == "3" %}Cupboard Dry
          {% elif DryT == "5" %}120'
          {% elif DryT == "6" %}90'
          {% elif DryT == "7" %}60'
          {% elif DryT == "8" %}30'
          {% elif DryT == "9" %}Wool Dry
          {% else %}{{ DryT | int // 60 }}
          {% endif %}
```

**Comment by Eikkargh** [comment]
Looks good. DryT == 4 (Dry Dinished) only comes up for a short time before PrPh == 5 (End). I think it corresponds to cool down time before the door is released. I kept it there to check for impending faults in the thermostat if it stays in this state longer.
