### ISSUE TITLE
Separate Dry Time from Dry Phase 

### ISSUE THREAD

**Issue by BenGlossop09** [Eikkargh/Candy-API-to-JSON#11]
As an enhancement, dry time and dry phases can be differentiated for model H3DS4965TACBE-80. Split 'Washer/Dryer - Dry Time' into appropriate 2 entities.

**Comment by Eikkargh** [comment]
Im not sure what you require here.

On my machine DryT is the data point for the drying setting selected on the touch display, not a numerical time. There is only 1 phase for a drying cycle `"PrPh" : "6",`. The data points TotalTime, RemTime and DelVal are the only time values.

As drying will always be after washing and delay, RemTime will show the remaining time on any program including drying ones. 

Data points for drying:
`Pr = { 12, 13 }` Drying Programs (Low, High)
`PrPh = { 6 }` Drying Phase
`DryT = { 0, 3, 4, 5 }`  Dry Time Setting (list of values not complete in yaml)
`RemTime = { int }` Remaining Dry Time (mins) + DelVal

**Comment by BenGlossop09** [comment]
You're correct here. 
For my machine, all of the DryT values are associated with time. Because of the updates to the DryT values in the other issue thread, it makes this thread mostly redundant. For example the entity 'Dry Setting' may display 60' or 120' - there isn't much need to duplicate that with another entity.
