### ISSUE TITLE
Add WiFi settings for WiFi command mode

### ISSUE THREAD

**Issue by Eikkargh** [Eikkargh/Candy-API-to-JSON#6]
Not much of an issue but the only feature not supported in the PrNm list is the WiFi setting. It doesn't appear to hold a unique value. I have not yet tested what the program entity will output when WiFi is selected and a wash is started - I would assume the machine will output the actual program selected. 

_Originally posted by @BenGlossop09 in https://github.com/Eikkargh/Candy-API-to-JSON/issues/5#issuecomment-2352374357_

**Comment by BenGlossop09** [comment]
I believe PrCode = 65 corresponds to "WiFi" (remote control mode). Until I know exactly what PrCode is, it's difficult to confirm 65 is definitely for WiFi mode.

**Comment by Eikkargh** [comment]
Sounds like a good start. Ill add this into the code with the other elements of [PrCode in configuration.yaml](https://github.com/Eikkargh/Candy-API-to-JSON/blob/7-add-keys-for-programs-with-additional-settings/H3DS4965TACBE-80_configuration.yaml) so it can record it in Home Assistant. My machine doesnt have PrCode so I can only go on what you discover.
