### ISSUE TITLE
Add keys for programs with additional settings

### ISSUE THREAD

**Issue by Eikkargh** [Eikkargh/Candy-API-to-JSON#7]
Rapid 14'/30'/44' do not each hold a unique program so are bundled together. 

_Originally posted by @BenGlossop09 in https://github.com/Eikkargh/Candy-API-to-JSON/issues/5#issuecomment-2352374357_

**Comment by Eikkargh** [comment]
Machine: H3DS4965TACBE-80
Pr/PrNm = 10 ( Rapid 14'/30'/44' )
Possibly involves key : value "PrCode" : "122". Unable to test as not an option on my machine.
To test remove `and k[0:3] != "PrC"` from line 50 of candy.py and add `- PrCode` to json_attributes of command_line sensor.

**Comment by BenGlossop09** [comment]
I added your suggested edits, the PrCode outputs are;
Wash 44' has PrCode = 103
30' = 71
14' = 39

I must put more time into learning python - how could this be integrated into the yaml? As it stands the program entity is only looking for "PrNm" values, adding the above values to the reference list would not work. I would suggest the logic should be 'look for PrNm value to determine the program, but if the PrNm result is 10 then lookup a separate reference table to find the subset program - If PrNm=10 then look for a PrCode and output the program name assigned to the PrCode value'.

**Comment by Eikkargh** [comment]
Python is very useful. As I said this was my first program and its a pretty straightforward language to pick up. 

With the changes it looks like you are getting a PrCode attribute from the command_line sensor so its down to whether you want to add this into the Program template like this: 
```
  - sensor:
      - name: 'Washer/Dryer - Program'
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'PrNm') %}
          {% set ProgC = state_attr('sensor.candy_washer_dryer', 'PrCode') %}
          {% if Prog == "2" %}Cotton
          {% elif Prog == "3" %}Eco 40-60
          {% elif Prog == "4" %}Cotton & Prewash
          {% elif Prog == "9" %}Wool & Soft Care
          {% elif Prog == "10" %}
            {% if ProgC == "103" %}Rapid 14'
            {% elif ProgC == "71" %}Rapid 30'
            {% elif ProgC == "39" %}Rapid 44'
            {% elif ProgC == "65" %}Wifi Command
            {% else %}{{ ProgC }}
          {% elif Prog == "11" %}All in One 59'
          {% elif Prog == "12" %}Extra Care
          {% elif Prog == "13" %}Dry (Wool)
          {% elif Prog == "14" %}Dry (Low Heat)
          {% elif Prog == "15" %}Dry (High Heat)
          {% elif Prog == None %}Off
          {% else %}{{ Prog }}
          {% endif %}
```
The above is the approach I have put into this update. Alternatively if you want a separate sensor for it you could try:
```
  - sensor:
      - name: 'Washer/Dryer - Sub Program'
        icon: mdi:progress-star
        state: >
          {% set ProgC = state_attr('sensor.candy_washer_dryer', 'PrCode') %}
          {% if ProgC == "103" %}Wash 44'
          {% elif ProgC == "71" %}Wash 30'
          {% elif ProgC == "39" %}Wash 14'
          {% elif ProgC == None %}Off
          {% else %}{{ ProgC }}
          {% endif %}
```
However this would also require adjustments to the dashboard side. 

Editted to add Wifi Command to Program template.

**Comment by BenGlossop09** [comment]
Slightly revised code provided which adds missing {% endif %} after ProgC. Tested as working for my machine.

```
  - sensor:
      - name: 'Washer/Dryer - Program'
        icon: mdi:progress-star
        state: >
          {% set Prog = state_attr('sensor.candy_washer_dryer', 'PrNm') %}
          {% set ProgC = state_attr('sensor.candy_washer_dryer', 'PrCode') %}
          {% if Prog == "2" %}Cotton
          {% elif Prog == "3" %}Eco 40-60
          {% elif Prog == "4" %}Cotton & Prewash
          {% elif Prog == "9" %}Wool & Soft Care
          {% elif Prog == "10" %}
            {% if ProgC == "39" %}Rapid 14'
            {% elif ProgC == "71" %}Rapid 30'
            {% elif ProgC == "103" %}Rapid 44'
            {% elif ProgC == "65" %}Wifi Command
            {% else %}{{ ProgC }}
            {% endif %}
          {% elif Prog == "11" %}All in One 59'
          {% elif Prog == "12" %}Extra Care
          {% elif Prog == "13" %}Dry (Wool)
          {% elif Prog == "14" %}Dry (Low Heat)
          {% elif Prog == "15" %}Dry (High Heat)
          {% elif Prog == None %}Off
          {% else %}{{ Prog }}
          {% endif %}
```

**Comment by Eikkargh** [comment]
Ahh yes well spotted. Thank you. Updated the code for this commit.
